- hosts: all
  become: yes
  tasks:
  - name: download mosquitto img
    command: docker pull eclipse-mosquitto

  - name: send docker files into vm
    copy: 
      src: ./mosquitto.conf
      dest: /home/admin/
      force: no


  - name: creation docker nginx
    docker_container:
      user: "0"
      name: mqtt
      image: eclipse-mosquitto
      ports:
        - 1883:1883
        - 9001:9001
      volumes:
        - /home/admin/mosquitto.conf:/mosquitto/config/mosquitto.conf
      state: started

  # - name: copy conf mqtt 
  #   command: docker cp ./mosquitto.conf mqtt:mosquitto/config

  # - name: restart mosquitto container
  #   command: docker restart mqtt
