---
- hosts: all
  become: yes
  tasks:
  - name: download Nginx image
    command: "docker pull nginx"

  # - name: update apt
  #   command: apt update 
  # - name: install certbot 
  #   command: apt install -y certbot
  # - name: use certbot
  #   command: certbot certonly -d latunecampusl3.tk --standalone -m thomas.colin@le-campus-numerique.fr --agree-tos --no-eff-email

  - name: send docker files into vm
    copy: 
      src: ./conf_nginx/
      dest: /home/admin/
      force: no

  - name: unit ssl 
    command: openssl dhparam -out /home/admin/dhparam.pem 2048

  - name: creation docker nginx
    docker_container:
      name: nginx
      image: nginx
      volumes:
        - /home/admin/:/etc/nginx
        - /etc/letsencrypt/:/etc/letsencrypt/:ro
        - /home/admin/dhparam.pem:/etc/nginx/dhparam.pem:ro
      state: started
      ports: 
        - "80:80"
        - "443:443"
      networks:
        - name: latunet
      recreate: yes

  # - name: copy conf ngninx 
  #   command: docker cp ./ nginx:/etc/nginx/

  # - name: certif into docker container
  #   command: docker cp /etc/letsencrypt/ nginx:/home/letsencrypt
  
  # - name: restart nginx
  #   command: docker restart nginx

  # - name: run docker-compose
  #   command: "docker-compose -y up"
  # - name: restart nginx
  #   command: docker exec -it nginx nginx
        # volumes:
      #   - ./conf_nginx/:/etc/nginx/
      #   - ./conf_nginx/sites-available/:/etc/nginx/sites-available/
      #   - ./conf_nginx/sites-enabled/:/etc/nginx/sites-enabled/
      #   - ./conf_nginx/nginxconfig.io/:/etc/nginx/nginxconfig.io/
      #   - ./conf_nginx/www/:/var/www/latune/public/

